[package]
name = "ansi_shim"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]

[dependencies]
vte = "0.3.2"
log = "0.4.1"
env_logger = "0.5.3"

[workspace]
members = [
    "ansi2win"
]
